kind: Deployment
apiVersion: v1
metadata:
  name: frontned
  namespace: expense
  labels:
    app: backend
    tier: backend
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: backend
      project: expense
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        project: expense
    spec:
      containers:
      - name: nginx
        image: kavya487/frontned:1.0.0
---
kind: Service
apiVersion: v1
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    app: frontend
    tier: frontend
    project: expense
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80