kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontned
  labels:
    app: frontend
    tier: frontned
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      tier: frontend
      project: expense
  template:
  metadata: 
    labels:
      app: frontend
      tier: frontend
      project: expense
    containers:
    - name: nginx
      image: kavya478/frontend:1.0.0 
---
kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    app: frontend
    tier: frontend
    project: expense
  ports:
  - protocol: TCP
    Port: 80
    targetPort: 80
