kind: Deployment
apiVersion: apps/v1
metadata:
  name: expense
  namespace: expense
  labels:
    app: backend
    tier: backend
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: backend
      project: expense
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        project: expense
    spec:
      containers:
      - name: nginx
        image: kavya478/backend:1.0.0
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
spec:
  
  selector:
    app: backend
    tier: backend
    project: expense
  ports:
  - protocol: TCP
    ports: 3306
    targetPort: 3306