kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: expense
  labels:
    app: mysql
    tier: mysql
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: mysql
      project: expense
  template:
    metadata:
      labels:
        app: mysql
        tier: mysql
        project: expense
    spec:
      containers:
      - name: nginx
        image: kavya478/mysql:1.0.0 
---
kind: Service
apiVersion: v1
metadata: 
  name: mysql
  namespace: expense
spec:
  selector:
    app: mysql
    tier: mysql
    project: expense
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306