kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: expense
  labels:
    app: mysql
    web: database

spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
      web: database
  template:
    metadata:
      labels:
        app: mysql
        web: database
    spec:
      containers:
      - name: mysql
        image: kavya478/mysql
# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: nginx
# spec:
#   type: Loadbalancer
#   selector:
#     app: mysql
#     web: database
#   ports:
#   - prototcol: TCP
#     port: 80
#     targetPort: 80
