apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense
  namespace: expense
  labels:
    app: mysql
    tier: mysql
    project: expense
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
      tier: mysql
      project: expense
  template:
    metadata:
      labels:
        app: mysql
        tier: mysql
        project: expense
    spec:  # <-- moved out of metadata
      containers:
        - name: nginx
          image: kavya478/mysql:1.0.0
